### ISSUE TITLE
Large steam library not syncing completely

### ISSUE THREAD

**Issue by aryko1872** [a-busman/Backlogger#52]
Hi, really like your app. It’s great

One issue: I synced with steam a few times and many of the games are not adding to my library in the app. I have a large steam library (1600+ games) and only about 1000 are syncing. Let me know if I can provide any more info to help troubleshoot

**Comment by a-busman** [comment]
Oh my. That's large. Does it just stall at about 1000 when it's spinning (it's slow btw since I can only make 1 request per second to the GiantBomb api)? Or is it after that during the selection in the table? I can add in some extra logging for events like if it's stalled after a certain amount of time, I can get a crashlytics event with the name of the game it stalls on just in case it's a certain game that is messing up the app or something. I can add this in my next version.

**Comment by aryko1872** [comment]
Awesome. Thanks for the quick response. It is large... I got carried away with bundles over the past few years ;)

The sync does not stall. It appears to complete, but then the next page shows no games to add.  

More info: the first sync found 1667 games but only added around 1000 games. Then the next three re-syncs added a handful of additional games, but now seems to not add any more each time I try.  Stays at 1037 it found and each subeseqnt sync always goes through the same number of 630 remaining but always results in an empty add games page.

I’m assuming after the sync there is some sort of lookup with GiantBomb and maybe some error or mistmatch there. When I search manually for the missing games they do show up (games like Borderlands 2 did not get added after sync, so I don’t think it’s a matching issue

Thanks again!

Happy New Year!!

**Comment by a-busman** [comment]
It sometimes can be a matching issue when you have multiple games but different editions of it. I dedupe the matches, and even in my own library of only about 250 games, I get about 6 or 7 incorrect matches that just match to completely wrong games. I search for the game name provided by steam, which often doesn't match with GiantBomb. I have been planning on doing direct matches for things that don't match properly, and this is a good idea to add in match logging (since I don't own nearly the entire steam library) so that I can make it match. I've also played with the idea of background matching, but there's limited background processing I can do, and I wouldn't want to drain battery in the background.

In 1.1 (1.0.10 is in review still), I'll add in this logging to send to me to see how many incorrect matches there are, what the detected dupes are, and then I can improve the matching.

**Comment by aryko1872** [comment]
Sounds good. Let me know if I can help in any way. Happy to beta test if it helps. 

My steam account ID is aryko1872 if you want to test with it

**Comment by a-busman** [comment]
I'm working on mapping steam IDs to GiantBomb IDs. I don't have many, but I now have logging to FireBase which gives every gamed mapped, and every game that it cannot find. Right now, I have it where if there are steam IDs not in the local DB, it will search for them. If it determines the found game is a duplicate, then it won't show up in the add section. I also made it more clear if there are no new games to add. @aryko1872 I can add you on testflight if you want to try out the latest.

**Comment by aryko1872** [comment]
Sounds great! Thanks for the offer. Happy to help test. For TestFlight, my email is adamrykowski@gmail.com.

**Comment by aryko1872** [comment]
Hi, I just installed the beta for 2.0.0, and I don’t see the option to sync steam. Am I missing something? Add Game defaults to search, and Import defaults to import from a file. Sorry if I’m missing something, it’s been a while since I’ve tried it

**Comment by a-busman** [comment]
Hey at the very top of the "More" page should be an option to link your steam account. If you are already signed in, you can go to the steam platform in your Library, and tap "More" in the upper right corner, and then tap "Sync with Steam"

**Comment by a-busman** [comment]
V2.0 should fix this 9a2fb1981a12b28eaec0091efaddc43ca50f5a2f

**Comment by aryko1872** [comment]
I’m signed into Steam but My library page is blank and there is no Steam platform listed 

Not sure how I got into this state, but this is likely a new issue 

![32CC5AD9-E03F-4974-A595-F1E8A166E737](https://user-images.githubusercontent.com/10803426/74604684-4287de00-508e-11ea-9589-4d6b1a5b9a8a.png)
![BF1BB960-18EB-48CC-AFEF-072984C93FA1](https://user-images.githubusercontent.com/10803426/74604685-43207480-508e-11ea-8f64-d5a60bee5a03.png)
